let project = new Project('found');
project.addAssets('defaults/**');
project.addSources('Sources');
project.addDefine("found");
project.addParameter('found.trait');
project.addParameter("--macro keep('found.trait')");
project.addParameter('found.node');
project.addParameter("--macro keep('found.node')");
project.addLibrary('Libraries/foundsdk/hxmath');
project.addLibrary('Libraries/foundsdk/echo');
project.addLibrary('Libraries/foundsdk/zui');
resolve(project);